[09/24/2021 09:03:59 PM] [LogPython 9152 ] [WARNING] Invalid action (--help)
[09/24/2021 09:03:59 PM] [LogPython 9152 ] [WARNING] Invalid action (--help)
[09/24/2021 09:04:12 PM] [LogPython 16132] [WARNING] Invalid action (--help)
[09/24/2021 09:16:01 PM] [LogPython 6160 ] [INFO   ] student_shedule
[09/24/2021 09:19:48 PM] [LogPython 5676 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 09:52:34 PM] [LogPython 19404] [WARNING] Invalid action (--help)
[09/24/2021 09:52:34 PM] [LogPython 19404] [INFO   ] 
[09/24/2021 09:53:04 PM] [LogPython 8320 ] [WARNING] Invalid action (--help)
[09/24/2021 09:53:04 PM] [LogPython 8320 ] [INFO   ] 
[09/24/2021 09:53:32 PM] [LogPython 9452 ] [WARNING] Invalid action (--help)
[09/24/2021 09:53:32 PM] [LogPython 9452 ] [ERROR  ] [Errno 2] No such file or directory: 'Абрютин Иван Дмитриевич.xlsx'
[09/24/2021 09:53:32 PM] [LogPython 9452 ] [INFO   ] 
[09/24/2021 09:53:58 PM] [LogPython 12176] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 09:54:28 PM] [LogPython 10684] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 09:55:48 PM] [LogPython 17344] [WARNING] Invalid action (--help)
[09/24/2021 09:55:48 PM] [LogPython 17344] [ERROR  ] 'Lesson' object is not iterable
[09/24/2021 09:55:48 PM] [LogPython 17344] [INFO   ] 
[09/24/2021 09:56:22 PM] [LogPython 12032] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:11:11 PM] [LogPython 15644] [WARNING] Invalid action (--help)
[09/24/2021 10:11:11 PM] [LogPython 15644] [ERROR  ] unsupported operand type(s) for -: 'str' and 'int'
[09/24/2021 10:11:11 PM] [LogPython 15644] [INFO   ] 
[09/24/2021 10:11:22 PM] [LogPython 14224] [WARNING] Invalid action (--help)
[09/24/2021 10:11:22 PM] [LogPython 14224] [ERROR  ] unsupported operand type(s) for -: 'str' and 'int'
[09/24/2021 10:11:22 PM] [LogPython 14224] [INFO   ] 
[09/24/2021 10:11:26 PM] [LogPython 19008] [WARNING] Invalid action (--help)
[09/24/2021 10:11:26 PM] [LogPython 19008] [ERROR  ] unsupported operand type(s) for -: 'str' and 'int'
[09/24/2021 10:11:26 PM] [LogPython 19008] [INFO   ] 
[09/24/2021 10:11:52 PM] [LogPython 18608] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:12:57 PM] [LogPython 13740] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:13:38 PM] [LogPython 11240] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:13:59 PM] [LogPython 1020 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:14:40 PM] [LogPython 18692] [WARNING] Invalid action (--help)
[09/24/2021 10:14:40 PM] [LogPython 18692] [ERROR  ] 'Day' object is not iterable
[09/24/2021 10:14:40 PM] [LogPython 18692] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:14:59 PM] [LogPython 14660] [WARNING] Invalid action (--help)
[09/24/2021 10:14:59 PM] [LogPython 14660] [ERROR  ] 'Day' object has no attribute 'name'
[09/24/2021 10:14:59 PM] [LogPython 14660] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:15:45 PM] [LogPython 8968 ] [WARNING] Invalid action (--help)
[09/24/2021 10:15:45 PM] [LogPython 8968 ] [ERROR  ] 'Lesson' object has no attribute 'schedule'
[09/24/2021 10:15:45 PM] [LogPython 8968 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:16:35 PM] [LogPython 11156] [WARNING] Invalid action (--help)
[09/24/2021 10:16:35 PM] [LogPython 11156] [ERROR  ] 'Lesson' object has no attribute 'schedule'
[09/24/2021 10:16:35 PM] [LogPython 11156] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:16:46 PM] [LogPython 18736] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:17:00 PM] [LogPython 18072] [WARNING] Invalid action (--help)
[09/24/2021 10:17:00 PM] [LogPython 18072] [ERROR  ] 'Day' object has no attribute 'teacher'
[09/24/2021 10:17:00 PM] [LogPython 18072] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:17:07 PM] [LogPython 10700] [WARNING] Invalid action (--help)
[09/24/2021 10:17:07 PM] [LogPython 10700] [ERROR  ] 'Lesson' object has no attribute 'schedule'
[09/24/2021 10:17:07 PM] [LogPython 10700] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:17:15 PM] [LogPython 19216] [WARNING] Invalid action (--help)
[09/24/2021 10:17:15 PM] [LogPython 19216] [ERROR  ] 'Day' object has no attribute 'teacher'
[09/24/2021 10:17:15 PM] [LogPython 19216] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:17:56 PM] [LogPython 9696 ] [WARNING] Invalid action (--help)
[09/24/2021 10:17:56 PM] [LogPython 9696 ] [ERROR  ] 'Day' object has no attribute 'teacher'
[09/24/2021 10:17:56 PM] [LogPython 9696 ] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    print(TEACHERS['Дятлов А.А.'][day].teacher)
AttributeError: 'Day' object has no attribute 'teacher'

[09/24/2021 10:17:56 PM] [LogPython 9696 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:18:42 PM] [LogPython 17696] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:19:45 PM] [LogPython 11956] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:21:24 PM] [LogPython 11916] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:21:59 PM] [LogPython 17696] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:22:30 PM] [LogPython 10656] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:22:40 PM] [LogPython 19088] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:22:48 PM] [LogPython 148  ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:23:22 PM] [LogPython 6988 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:23:43 PM] [LogPython 13092] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:25:14 PM] [LogPython 12332] [WARNING] Invalid action (--help)
[09/24/2021 10:25:14 PM] [LogPython 12332] [ERROR  ] 'Ляпин Н.А.'
[09/24/2021 10:25:14 PM] [LogPython 12332] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 108, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 75, in update
    TEACHERS[teacher_name][current_day.title].update_schedule(
KeyError: 'Ляпин Н.А.'

[09/24/2021 10:25:14 PM] [LogPython 12332] [INFO   ] 
[09/24/2021 10:28:03 PM] [LogPython 19196] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:28:44 PM] [LogPython 9264 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:29:22 PM] [LogPython 16760] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:29:55 PM] [LogPython 10652] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:30:37 PM] [LogPython 10684] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:30:58 PM] [LogPython 19188] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:31:13 PM] [LogPython 4036 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:32:38 PM] [LogPython 16940] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:32:59 PM] [LogPython 13564] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:33:38 PM] [LogPython 19348] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:34:08 PM] [LogPython 15632] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:36:02 PM] [LogPython 18752] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:37:28 PM] [LogPython 2960 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:39:30 PM] [LogPython 16740] [WARNING] Invalid action (--help)
[09/24/2021 10:39:30 PM] [LogPython 16740] [ERROR  ] 'Понедельник'
[09/24/2021 10:39:30 PM] [LogPython 16740] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 106, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 73, in update
    TEACHERS[teacher_name][current_day.title].schedule = ['Окно' for i in range(8)]
KeyError: 'Понедельник'

[09/24/2021 10:39:30 PM] [LogPython 16740] [INFO   ] 
[09/24/2021 10:39:52 PM] [LogPython 19128] [WARNING] Invalid action (--help)
[09/24/2021 10:39:52 PM] [LogPython 19128] [ERROR  ] 'dict' object has no attribute 'schedule'
[09/24/2021 10:39:52 PM] [LogPython 19128] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 74, in update
    TEACHERS[teacher_name][current_day.title].schedule = ['Окно' for i in range(8)]
AttributeError: 'dict' object has no attribute 'schedule'

[09/24/2021 10:39:52 PM] [LogPython 19128] [INFO   ] 
[09/24/2021 10:40:08 PM] [LogPython 2784 ] [WARNING] Invalid action (--help)
[09/24/2021 10:40:08 PM] [LogPython 2784 ] [ERROR  ] 'Day' object has no attribute 'shedule'
[09/24/2021 10:40:08 PM] [LogPython 2784 ] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].shedule[first_column - 1] = current_lesson
AttributeError: 'Day' object has no attribute 'shedule'

[09/24/2021 10:40:08 PM] [LogPython 2784 ] [INFO   ] 
[09/24/2021 10:40:09 PM] [LogPython 2980 ] [WARNING] Invalid action (--help)
[09/24/2021 10:40:09 PM] [LogPython 2980 ] [ERROR  ] 'Day' object has no attribute 'shedule'
[09/24/2021 10:40:09 PM] [LogPython 2980 ] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].shedule[first_column - 1] = current_lesson
AttributeError: 'Day' object has no attribute 'shedule'

[09/24/2021 10:40:09 PM] [LogPython 2980 ] [INFO   ] 
[09/24/2021 10:40:10 PM] [LogPython 18904] [WARNING] Invalid action (--help)
[09/24/2021 10:40:10 PM] [LogPython 18904] [ERROR  ] 'Day' object has no attribute 'shedule'
[09/24/2021 10:40:10 PM] [LogPython 18904] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].shedule[first_column - 1] = current_lesson
AttributeError: 'Day' object has no attribute 'shedule'

[09/24/2021 10:40:10 PM] [LogPython 18904] [INFO   ] 
[09/24/2021 10:40:10 PM] [LogPython 18408] [WARNING] Invalid action (--help)
[09/24/2021 10:40:10 PM] [LogPython 18408] [ERROR  ] 'Day' object has no attribute 'shedule'
[09/24/2021 10:40:10 PM] [LogPython 18408] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].shedule[first_column - 1] = current_lesson
AttributeError: 'Day' object has no attribute 'shedule'

[09/24/2021 10:40:10 PM] [LogPython 18408] [INFO   ] 
[09/24/2021 10:40:21 PM] [LogPython 19420] [WARNING] Invalid action (--help)
[09/24/2021 10:40:21 PM] [LogPython 19420] [ERROR  ] unsupported operand type(s) for -: 'str' and 'int'
[09/24/2021 10:40:21 PM] [LogPython 19420] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].schedule[first_column - 1] = current_lesson
TypeError: unsupported operand type(s) for -: 'str' and 'int'

[09/24/2021 10:40:21 PM] [LogPython 19420] [INFO   ] 
[09/24/2021 10:40:22 PM] [LogPython 9616 ] [WARNING] Invalid action (--help)
[09/24/2021 10:40:22 PM] [LogPython 9616 ] [ERROR  ] unsupported operand type(s) for -: 'str' and 'int'
[09/24/2021 10:40:22 PM] [LogPython 9616 ] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].schedule[first_column - 1] = current_lesson
TypeError: unsupported operand type(s) for -: 'str' and 'int'

[09/24/2021 10:40:22 PM] [LogPython 9616 ] [INFO   ] 
[09/24/2021 10:40:35 PM] [LogPython 13644] [WARNING] Invalid action (--help)
[09/24/2021 10:40:35 PM] [LogPython 13644] [ERROR  ] 'Вторник'
[09/24/2021 10:40:35 PM] [LogPython 13644] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 76, in update
    TEACHERS[teacher_name][current_day.title].schedule[int(first_column)- 1] = current_lesson
KeyError: 'Вторник'

[09/24/2021 10:40:35 PM] [LogPython 13644] [INFO   ] 
[09/24/2021 10:41:41 PM] [LogPython 14060] [WARNING] Invalid action (--help)
[09/24/2021 10:41:41 PM] [LogPython 14060] [ERROR  ] list assignment index out of range
[09/24/2021 10:41:41 PM] [LogPython 14060] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 109, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 78, in update
    TEACHERS[teacher_name][current_day.title].schedule[int(first_column)- 1] = current_lesson
IndexError: list assignment index out of range

[09/24/2021 10:41:41 PM] [LogPython 14060] [INFO   ] 
[09/24/2021 10:42:28 PM] [LogPython 3768 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:42:39 PM] [LogPython 9688 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:43:50 PM] [LogPython 15780] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:44:57 PM] [LogPython 12864] [WARNING] Invalid action (--help)
[09/24/2021 10:44:57 PM] [LogPython 12864] [ERROR  ] 'str' object has no attribute 'group'
[09/24/2021 10:44:57 PM] [LogPython 12864] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 109, in handler
    print(lesson.group)
AttributeError: 'str' object has no attribute 'group'

[09/24/2021 10:44:57 PM] [LogPython 12864] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:45:32 PM] [LogPython 4420 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:46:05 PM] [LogPython 9916 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:46:25 PM] [LogPython 13428] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:47:34 PM] [LogPython 19116] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:48:47 PM] [LogPython 14660] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:49:04 PM] [LogPython 15652] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:49:32 PM] [LogPython 16708] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:50:48 PM] [LogPython 13252] [WARNING] Invalid action (--help)
[09/24/2021 10:50:48 PM] [LogPython 13252] [ERROR  ] 'Day' object has no attribute 'teacher'
[09/24/2021 10:50:48 PM] [LogPython 13252] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 109, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 80, in update
    print(current_day.title, current_day.teacher)
AttributeError: 'Day' object has no attribute 'teacher'

[09/24/2021 10:50:48 PM] [LogPython 13252] [INFO   ] 
[09/24/2021 10:50:59 PM] [LogPython 19324] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:51:30 PM] [LogPython 16968] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:51:53 PM] [LogPython 18932] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:53:13 PM] [LogPython 13184] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:53:28 PM] [LogPython 18800] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:54:15 PM] [LogPython 15008] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:54:45 PM] [LogPython 5816 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:56:06 PM] [LogPython 7624 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:58:33 PM] [LogPython 6396 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:58:52 PM] [LogPython 9292 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 10:59:35 PM] [LogPython 17644] [WARNING] Invalid action (--help)
[09/24/2021 10:59:35 PM] [LogPython 17644] [ERROR  ] 'Дятлов А.А.'
[09/24/2021 10:59:35 PM] [LogPython 17644] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 111, in handler
    for day in TEACHERS['Дятлов А.А.']:
KeyError: 'Дятлов А.А.'

[09/24/2021 10:59:35 PM] [LogPython 17644] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:00:21 PM] [LogPython 12772] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:00:49 PM] [LogPython 9120 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:01:56 PM] [LogPython 4768 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:02:42 PM] [LogPython 18608] [WARNING] Invalid action (--help)
[09/24/2021 11:02:42 PM] [LogPython 18608] [ERROR  ] ''
[09/24/2021 11:02:42 PM] [LogPython 18608] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 106, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 79, in update
    TEACHERS[teacher_name][current_day.title] = current_day
KeyError: ''

[09/24/2021 11:02:42 PM] [LogPython 18608] [INFO   ] 
[09/24/2021 11:03:17 PM] [LogPython 19244] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:03:29 PM] [LogPython 16024] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:05:16 PM] [LogPython 8868 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:05:29 PM] [LogPython 10748] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:06:45 PM] [LogPython 11540] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:07:04 PM] [LogPython 16280] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:07:33 PM] [LogPython 4692 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:08:19 PM] [LogPython 9676 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:09:31 PM] [LogPython 19192] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:10:04 PM] [LogPython 11208] [WARNING] Invalid action (--help)
[09/24/2021 11:10:04 PM] [LogPython 11208] [ERROR  ] ''
[09/24/2021 11:10:04 PM] [LogPython 11208] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 107, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 80, in update
    TEACHERS[teacher_name][current_day.title] = current_day
KeyError: ''

[09/24/2021 11:10:04 PM] [LogPython 11208] [INFO   ] 
[09/24/2021 11:10:41 PM] [LogPython 19160] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:12:24 PM] [LogPython 5604 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:12:38 PM] [LogPython 15264] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:13:05 PM] [LogPython 18940] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:15:22 PM] [LogPython 80   ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:17:10 PM] [LogPython 7620 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:18:22 PM] [LogPython 15324] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:18:54 PM] [LogPython 18736] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:20:02 PM] [LogPython 9916 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:21:46 PM] [LogPython 15020] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:21:56 PM] [LogPython 11428] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:22:41 PM] [LogPython 2092 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:23:00 PM] [LogPython 9264 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:24:47 PM] [LogPython 18616] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:25:42 PM] [LogPython 19168] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:26:02 PM] [LogPython 1792 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:27:08 PM] [LogPython 12936] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:28:11 PM] [LogPython 14372] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:30:45 PM] [LogPython 19300] [WARNING] Invalid action (--help)
[09/24/2021 11:30:45 PM] [LogPython 19300] [ERROR  ] 'Ляпин Н.А.'
[09/24/2021 11:30:45 PM] [LogPython 19300] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 110, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 72, in update
    print(teacher_name, TEACHERS[teacher_name])
KeyError: 'Ляпин Н.А.'

[09/24/2021 11:30:45 PM] [LogPython 19300] [INFO   ] 
[09/24/2021 11:30:51 PM] [LogPython 18736] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:33:33 PM] [LogPython 19176] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:34:21 PM] [LogPython 14620] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:34:45 PM] [LogPython 19400] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:35:25 PM] [LogPython 4400 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:35:37 PM] [LogPython 3052 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:36:30 PM] [LogPython 10488] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:37:14 PM] [LogPython 9272 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:37:45 PM] [LogPython 18928] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:39:06 PM] [LogPython 17644] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:39:43 PM] [LogPython 9536 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:42:22 PM] [LogPython 6696 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:42:41 PM] [LogPython 18860] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:43:13 PM] [LogPython 11804] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:43:31 PM] [LogPython 3612 ] [INFO   ] Successfully updated -> Teacher.update
[09/24/2021 11:43:49 PM] [LogPython 7100 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:42:48 PM] [LogPython 9844 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:43:01 PM] [LogPython 3612 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:44:02 PM] [LogPython 3128 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:48:24 PM] [LogPython 6824 ] [WARNING] Invalid action (--help)
[09/25/2021 01:48:24 PM] [LogPython 6824 ] [ERROR  ] 'NoneType' object has no attribute 'title'
[09/25/2021 01:48:24 PM] [LogPython 6824 ] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 112, in handler
    method = getattr(sample, t)()
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 77, in update
    TEACHERS[teacher_name][current_day.title] = Day(day_title)
AttributeError: 'NoneType' object has no attribute 'title'

[09/25/2021 01:48:24 PM] [LogPython 6824 ] [INFO   ] 
[09/25/2021 01:48:47 PM] [LogPython 1236 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:48:59 PM] [LogPython 7352 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:49:31 PM] [LogPython 11804] [WARNING] Invalid action (--help)
[09/25/2021 01:49:31 PM] [LogPython 11804] [ERROR  ] 'str' object has no attribute 'group'
[09/25/2021 01:49:31 PM] [LogPython 11804] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 116, in handler
    print(lesson, lesson.group)
AttributeError: 'str' object has no attribute 'group'

[09/25/2021 01:49:31 PM] [LogPython 11804] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:51:18 PM] [LogPython 12068] [WARNING] Invalid action (--help)
[09/25/2021 01:51:18 PM] [LogPython 12068] [ERROR  ] 'str' object has no attribute 'group'
[09/25/2021 01:51:18 PM] [LogPython 12068] [ERROR  ] Traceback (most recent call last):
  File "D:\Dev\Ideas\new__pum_tg__\data\handler.py", line 116, in handler
    print(lesson, lesson.group)
AttributeError: 'str' object has no attribute 'group'

[09/25/2021 01:51:18 PM] [LogPython 12068] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:51:34 PM] [LogPython 7276 ] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 01:52:58 PM] [LogPython 12920] [INFO   ] Successfully updated -> Teacher.update
[09/25/2021 02:07:22 PM] [LogPython 7224 ] [INFO   ] Successfully updated -> Teacher.update
